---
commitizen:
  annotated_tag: true
  changelog_file: changelog.md
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 2.6.0
  version_files:
  - app/main.py:version
  version_scheme: semver
