name: Generate Changelog

on:
  push:
    branches:
      - main  

jobs:
  changelog:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Set up Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: '14'  

      - name: Install git-changelog
        run: |
          npm install -g git-changelog 

      - name: Generate Changelog
        run: |
            git changelog > changelog.md  
  
      - name: Configure git
        run: |
            git config --global user.name "andrew001s"  
            git config --global user.email "andrew001s+<algo>@users.noreply.github.com"

      - name: Commit and push changelog
        run: |
          git add changelog.md  
          git commit -m "chore: update changelog"  
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/andrew001s/SandyCore.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
