name: Generate Changelog

on:
  push:
    branches:
      - main  

jobs:
  changelog:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  #

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Instala las dependencias del proyecto
          pip install python-semantic-release  # Instala python-semantic-release

      - name: Generate Changelog
        run: |
          python -m semantic_release changelog  # Genera el changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: Commit and push changelog
        run: |
          git add changelog.md  # Asegúrate de que el archivo changelog.md esté añadido
          git commit -m "chore: update changelog"  # Realiza el commit del changelog generado
          git push  # Empuja los cambios al repositorio
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
