name: Generate Changelog

on:
  push:
    branches:
      - main  

jobs:
  changelog:
    runs-on: ubuntu-latest  
    steps:
      # Paso 1: Clonar el código
      - name: Checkout code
        uses: actions/checkout@v2  

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: '14'  

      # Paso 3: Instalar git-changelog
      - name: Install git-changelog
        run: |
          npm install -g git-changelog 

      # Paso 4: Verificar que git-changelog está instalado
      - name: Check git-changelog version
        run: |
          git-changelog --version

      # Paso 5: Verificar existencia de archivo .changelogrc
      - name: Verify changelogrc file
        run: |
          cat .changelogrc

      # Paso 6: Verificar existencia de archivo CHANGELOG.md antes de la ejecución
      - name: Check if CHANGELOG.md exists before
        run: |
          ls -l changelog.md || echo "No changelog.md file"

      # Paso 7: Generar el changelog
      - name: Generate Changelog
        run: |
          git changelog > changelog.md

      # Paso 8: Verificar existencia del archivo changelog.md después de la ejecución
      - name: Check if CHANGELOG.md exists after
        run: |
          ls -l changelog.md || echo "No changelog.md file generated"

      # Paso 9: Configuración de Git
      - name: Configure git
        run: |
            git config --global user.name "${{ secrets.GIT_USER_NAME }}"
            git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
            git fetch --tags

      # Paso 10: Verificar que el archivo changelog.md fue generado correctamente
      - name: Verify changelog content
        run: |
          cat changelog.md || echo "No content in changelog.md"

      # Paso 11: Commit y push del changelog
      - name: Commit and push changelog
        run: |
          git add changelog.md
          git commit -m "chore: update changelog"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
